# Last Update: 08/01/2022
# Dependents: AllocationsAmounts_fact.py
# Purpose: To assign a single value to the PrimaryUseCategory field for water rights.
# Notes 1) The BUtoWBUDict dictionary for converting Native Beneficial Use -> WaDE Beneficial Use will have to be updated everytime there is a native new benefical use added to the QA.


# Needed Libraries
############################################################################
import os
import numpy as np
import pandas as pd


# Dictionaries
############################################################################
# Native Beneficial Use -> WaDE Beneficial Use
BUtoWBUDict = {
"0 release for enviroment" : "Other",
"3 storage" : "Reservoir Storage",
"72-12-1 construction of public works" : "Commercial/Industrial",
"72-12-1 domestic and livestock watering" : "Domestic",
"72-12-1 domestic one household" : "Domestic",
"72-12-1 livestock watering" : "Livestock",
"72-12-1 multiple domestic households" : "Domestic",
"72-12-1 prospecting or development of natural resource" : "Other",
"72-12-1 sanitary in conjunction with a commercial use" : "Commercial/Industrial",
"administrative" : "Other",
"aesthetic" : "Municipal Irrigation",
"aesthetic from storage" : "Municipal Irrigation",
"aesthetic storage" : "Municipal Irrigation",
"aesthetics" : "Municipal Irrigation",
"agricultural" : "Agriculture Irrigation",
"agricultural consumptive use" : "Agriculture Irrigation",
"agricultural spraying" : "Agriculture Irrigation",
"agriculture" : "Agriculture Irrigation",
"agriculture - wetland" : "Agriculture Irrigation",
"agriculture other than irrigation" : "Agriculture Irrigation",
"agriculture uses" : "Agriculture Irrigation",
"air conditioning" : "Other",
"air conditioning or heating" : "Thermoelectric Cooling",
"all beneficial uses" : "Unspecified",
"anadromous and resident fish habitat (instream)" : "In-stream Flow",
"any purpose" : "Unspecified",
"aquaculture" : "Aquaculture",
"aquatic life (instream)" : "In-stream Flow",
"aquifer recharge" : "Aquifer Recharge",
"as decreed" : "Unspecified",
"augmentation" : "Unspecified",
"bed and banks" : "In-stream Flow",
"bottling" : "Commercial/Industrial",
"campsite" : "Recreation",
"cemetery" : "Municipal Irrigation",
"chemical" : "Commercial/Industrial",
"closed file" : "Unspecified",
"coal bed methane - ground water" : "Mining",
"combined uses" : "Unspecified",
"commercial" : "Commercial/Industrial",
"commercial (self-supplied)" : "Commercial/Industrial",
"commercial & indust" : "Commercial/Industrial",
"commercial from storage" : "Commercial/Industrial",
"commercial institutional" : "Commercial/Industrial",
"commercial storage" : "Commercial/Industrial",
"commercial uses" : "Commercial/Industrial",
"community type use" : "Public Supply",
"construction" : "Commercial/Industrial",
"consumptive instream flow" : "In-stream Flow",
"cooling" : "Thermoelectric Cooling",
"cooling for indust proces" : "Thermoelectric Cooling",
"cooling from storage" : "Thermoelectric Cooling",
"cooling storage" : "Thermoelectric Cooling",
"cranberry" : "Agriculture Irrigation",
"cultivation of fish" : "Aquaculture",
"cumulative accretion to river" : "In-stream Flow",
"dairy" : "Livestock",
"dairy barn uses" : "Livestock",
"dairy operation" : "Livestock",
"dcii" : "Other",
"dewatering" : "Other",
"dewatering well" : "Other",
"discharge" : "Other",
"diversion to storage" : "Reservoir Storage",
"divtotal" : "Other",
"domestic" : "Domestic",
"domestic - ground water" : "Domestic",
"domestic - surface water" : "Domestic",
"domestic (self-supplied)" : "Domestic",
"domestic and livestock" : "Domestic",
"domestic and livestock & livestock" : "Domestic",
"domestic construction" : "Domestic",
"domestic expanded" : "Domestic",
"domestic from storage" : "Domestic",
"domestic general" : "Domestic",
"domestic including lawn and garden" : "Domestic",
"domestic multiple" : "Domestic",
"domestic single" : "Domestic",
"domestic storage" : "Domestic",
"domestic supply" : "Domestic",
"domestic use" : "Domestic",
"dust control" : "Other",
"environmental" : "Other",
"environmental quality" : "Other",
"erosion control" : "Other",
"evaporation" : "Other",
"evaporative" : "Other",
"exploration" : "Other",
"export from basin" : "Other",
"export from state" : "Other",
"exports/imports" : "Other",
"federal reserved" : "Other",
"federal reserved use" : "Other",
"feed pen operation" : "Livestock",
"fire" : "Fire",
"fire protection" : "Fire",
"fire protection (instream)" : "In-stream Flow",
"fire protection from storage" : "Fire",
"fire protection storage" : "Fire",
"fish & wildlife" : "In-stream Flow",
"fish and game propogation" : "In-stream Flow",
"fish and wildlife" : "In-stream Flow",
"fish and wildlife preservation and enhancement" : "In-stream Flow",
"fish and wildlife propagation" : "In-stream Flow",
"fish culture" : "Aquaculture",
"fish habitat" : "Aquaculture",
"fish habitat storage" : "Aquaculture",
"fish propagation" : "Aquaculture",
"fish propagation from storage" : "Aquaculture",
"fish propagation storage" : "Aquaculture",
"fish raceways" : "Aquaculture",
"fishery" : "Aquaculture",
"fishery enhancement (instream)" : "In-stream Flow",
"flood control" : "Other",
"flood control permit" : "Other",
"flood control storage" : "Other",
"flow augmentation" : "Other",
"flow through" : "Other",
"flow through fish pond" : "Other",
"forest management" : "Other",
"frost protection" : "Other",
"game preserves" : "Other",
"geo-thermal (heating & cooling)" : "Thermoelectric Cooling",
"geo-thermal(energy production)" : "Thermoelectric Cooling",
"geothermal" : "Thermoelectric Cooling",
"geothermal boreholes" : "Thermoelectric Cooling",
"geothermal heating" : "Thermoelectric Cooling",
"greenhouse" : "Other",
"ground water recharge" : "Aquifer Recharge",
"ground water recharge from storage" : "Aquifer Recharge",
"ground water recharge storage" : "Aquifer Recharge",
"ground water remediation" : "Aquifer Recharge",
"groundwater aquifer storage & recovery" : "Aquifer Recharge",
"groundwater preservation" : "Aquifer Recharge",
"groundwater recharge" : "Aquifer Recharge",
"group domestic" : "Domestic",
"harvesting of cranberries" : "Agriculture Irrigation",
"heat control" : "Thermoelectric Cooling",
"heat exchange" : "Thermoelectric Cooling",
"heat protection for crops" : "Thermoelectric Cooling",
"heating" : "Thermoelectric Cooling",
"highway" : "Commercial/Industrial",
"highway construction" : "Commercial/Industrial",
"household use only" : "Domestic",
"human consumption" : "Domestic",
"human consumption and livestock" : "Domestic",
"hydroelectric" : "Hydroelectric",
"hydroelectric - priority" : "Hydroelectric",
"hydropower" : "Hydroelectric",
"incidental power" : "Unspecified",
"incidental underground storage" : "Aquifer Recharge",
"indian" : "Other",
"induced ground water recharge" : "Aquifer Recharge",
"industrial" : "Commercial/Industrial",
"industrial - ground water" : "Commercial/Industrial",
"industrial - power generation" : "Commercial/Industrial",
"industrial - salt water" : "Commercial/Industrial",
"industrial - surface water" : "Commercial/Industrial",
"industrial (self-supplied)" : "Commercial/Industrial",
"industrial cooling" : "Commercial/Industrial",
"industrial from storage" : "Commercial/Industrial",
"industrial storage" : "Commercial/Industrial",
"industrial use" : "Commercial/Industrial",
"industrial/manufacturing uses" : "Commercial/Industrial",
"injection" : "Aquifer Recharge",
"institution" : "Municipal Irrigation",
"institutional" : "Municipal Irrigation",
"instream" : "In-stream Flow",
"instream fishery" : "Aquaculture",
"instream flow" : "In-stream Flow",
"instream flow requirements" : "In-stream Flow",
"intentional underground storage" : "Aquifer Recharge",
"irrigated agriculture" : "Agriculture Irrigation",
"irrigation" : "Agriculture Irrigation",
"irrigation - ground water" : "Agriculture Irrigation",
"irrigation - surface water" : "Agriculture Irrigation",
"irrigation and domestic" : "Agriculture Irrigation",
"irrigation and incidental underground storage" : "Agriculture Irrigation",
"irrigation and storage (an appropriation approved for both uses)" : "Agriculture Irrigation",
"irrigation from natural stream" : "Agriculture Irrigation",
"irrigation from storage" : "Agriculture Irrigation",
"irrigation of cranberries" : "Agriculture Irrigation",
"irrigation storage" : "In-stream Flow",
"irrigation-carey act" : "Agriculture Irrigation",
"irrigation-dle" : "Agriculture Irrigation",
"laboratory" : "Commercial/Industrial",
"lake level maintenance" : "In-stream Flow",
"landscape irrigation" : "Municipal Irrigation",
"lawn and garden" : "Municipal Irrigation",
"livestock" : "Livestock",
"livestock (self-supplied)" : "Livestock",
"log deck sprinkling" : "Commercial/Industrial",
"m & i" : "Public Supply",
"maintain level of a lake" : "Recreation",
"major and minor reservoirs" : "Reservoir Storage",
"managed wetlands" : "In-stream Flow",
"manufacturing" : "Commercial/Industrial",
"marketing for mitigation/aquifer recharge" : "Aquifer Recharge",
"mechanical" : "Commercial/Industrial",
"medicinal" : "Commercial/Industrial",
"military - military installations" : "Commercial/Industrial",
"milling" : "Mining",
"minerals" : "Mining",
"minimum stream flow" : "In-stream Flow",
"minimum streamflow" : "In-stream Flow",
"mining" : "Mining",
"mining (self-supplied)" : "Mining",
"mining and milling" : "Mining",
"mining from storage" : "Mining",
"mining milling and dewatering" : "Mining",
"mining or milling or oil" : "Mining",
"mining storage" : "Mining",
"miscellaneous - ground water" : "Aquifer Recharge",
"mitigation" : "Other",
"mitigation by non-use" : "Other",
"mitigation water" : "Other",
"mobile home parks" : "Domestic",
"monitoring well" : "Aquifer Recharge",
"multi family residential" : "Public Supply",
"multi use" : "Other",
"multiple domestic" : "Domestic",
"multiple instream uses" : "In-stream Flow",
"multiple purpose" : "Other",
"multiple use" : "Domestic",
"municipal" : "Public Supply",
"municipal - city or county supplied water" : "Public Supply",
"municipal - ground water" : "Public Supply",
"municipal - surface water" : "Public Supply",
"municipal from storage" : "Public Supply",
"municipal storage" : "Municipal Irrigation",
"municipal use" : "Public Supply",
"municipal uses" : "Public Supply",
"municipal/domestic and livestock" : "Domestic",
"municipal/industrial" : "Municipal Irrigation",
"navigation" : "Other",
"no purpose identified" : "Unspecified",
"no right" : "Unspecified",
"no use of right or pod" : "Unspecified",
"non 72-12-1 domestic and livestock watering" : "Domestic",
"non 72-12-1 domestic one household" : "Domestic",
"non 72-12-1 livestock watering" : "Livestock",
"non 72-12-1 multiple domestic households" : "Domestic",
"non consumptive" : "Other",
"non-consumptive" : "Other",
"non-profit organizational use" : "Other",
"nonconsumptive" : "Other",
"not classified" : "Unspecified",
"nursery uses" : "Agriculture Irrigation",
"observation" : "Aquifer Recharge",
"observation and testing" : "Aquifer Recharge",
"oil" : "Commercial/Industrial",
"oil field maintenance" : "Commercial/Industrial",
"oil production" : "Commercial/Industrial",
"oil well flooding" : "Commercial/Industrial",
"other" : "Other",
"other (fish hatchery)" : "Aquaculture",
"other purpose" : "Other",
"other pws" : "Other",
"other spillway/floodgat" : "Other",
"pollution abatement" : "Other",
"pollution abatement (instream)" : "Other",
"pollution control well" : "Other",
"pond maintenance" : "Municipal Irrigation",
"potable supply" : "Public Supply",
"power" : "Unspecified",
"power (self-supplied)" : "Unspecified",
"power and incidental underground storage" : "Unspecified",
"power development" : "Unspecified",
"power from storage" : "Hydroelectric",
"power generation" : "Hydroelectric",
"power storage" : "Hydroelectric",
"practicably irrigable acreage" : "Agriculture Irrigation",
"primary and supplemental irrigation" : "Agriculture Irrigation",
"public parks" : "Municipal Irrigation",
"public supply" : "Municipal Irrigation",
"public utility" : "Municipal Irrigation",
"public water supply" : "Municipal Irrigation",
"quasi-municipal" : "Domestic",
"quasi-municipal uses" : "Domestic",
"railroad" : "Commercial/Industrial",
"railway" : "Commercial/Industrial",
"raise dam (for increase in head for power production)" : "Hydroelectric",
"ram" : "Commercial/Industrial",
"recharge" : "Aquifer Recharge",
"recreation" : "Recreation",
"recreation - beautification" : "Recreation",
"recreation fish wildlife" : "Recreation",
"recreation from storage" : "Recreation",
"recreation storage" : "Recreation",
"recreational" : "Recreation",
"required delta outflow" : "In-stream Flow",
"reservoir evaporation" : "Other",
"reservoir supply" : "Reservoir Storage",
"restroom" : "Domestic",
"reuse" : "Treated Wastewater/Reuse",
"riparian habitat (instream)" : "In-stream Flow",
"riparian habitat restoration project" : "In-stream Flow",
"road construction" : "Commercial/Industrial",
"rural water" : "Public Supply",
"rural water system" : "Public Supply",
"sale" : "Commercial/Industrial",
"sawmill" : "Commercial/Industrial",
"school use" : "Municipal Irrigation",
"secondary recovery of oil" : "Commercial/Industrial",
"sediment control" : "Other",
"shop" : "Commercial/Industrial",
"single family residential" : "Public Supply",
"snow making" : "Snow",
"stage" : "Other",
"stock" : "Livestock",
"stock and domestic" : "Livestock",
"stock water" : "Livestock",
"stock watering" : "Livestock",
"stockpond" : "Livestock",
"stockraising" : "Livestock",
"stockwater" : "Livestock",
"stockwater from storage" : "Livestock",
"stockwater storage" : "Livestock",
"stockwatering" : "Livestock",
"storage" : "Reservoir Storage",
"storage and incidental underground storage" : "Aquifer Recharge",
"storage use-only" : "Reservoir Storage",
"stream" : "In-stream Flow",
"stream augmentation" : "In-stream Flow",
"subdivision" : "Public Supply",
"suburban housing development" : "Public Supply",
"supplemental cooling" : "Thermoelectric Cooling",
"supplemental fish culture" : "Aquaculture",
"supplemental flood harvesting" : "Other",
"supplemental irrigation" : "Agriculture Irrigation",
"supplemental irrigation and incidental underground storage" : "Agriculture Irrigation",
"supplemental power" : "Hydroelectric",
"supplemental power and incidental underground storage" : "Hydroelectric",
"supplemental storage" : "Reservoir Storage",
"swimming" : "Recreation",
"temperature control" : "Thermoelectric Cooling",
"temporary" : "Other",
"temporary transfer to in-stream use" : "Other",
"to be determined" : "Unspecified",
"total" : "Unspecified",
"transmountain export" : "Other",
"undetermined" : "Unspecified",
"unknown" : "Unspecified",
"unspecified" : "Unspecified",
"unused" : "Other",
"urban" : "Public Supply",
"use in a mint still" : "Public Supply",
"use within a school" : "Public Supply",
"waste storage" : "Treated Wastewater/Reuse",
"water marketing" : "Other",
"water quality" : "Other",
"water quality improvement" : "Other",
"water quality improvement storage" : "Other",
"water quality improvement from storage" : "Other",
"waterfowl" : "Other",
"wetland" : "Other",
"wetland mitigation credit" : "Other",
"wetlands" : "Other",
"wild and scenic river" : "Other",
"wildlife" : "Other",
"wildlife from storage" : "Other",
"wildlife habitat" : "Other",
"wildlife habitat maintenance and enhancement" : "Other",
"wildlife management" : "Other",
"wildlife refuge" : "Other",
"wildlife storage" : "Other",
"wildlife/waterfowl" : "Other",
"diversion out of basin" : "Other",
"poultry and egg operation" : "Commercial/Industrial",
"stacked water right" : "Unspecified",
"cathodic protection well" : "Unspecified",
"augmentation well" : "Unspecified",
"meat packing plant" : "Commercial/Industrial",
"petroleum processing plant" : "Commercial/Industrial",
"strategic water reserve" : "Reservoir Storage",
"brine production well" : "Commercial/Industrial",
"undefined" : "Undefined",
"ice cutting" : "Other",
"monitor" : "Aquifer Recharge",
"transportation" : "Commercial/Industrial",
"coal bed natural gas" : "Mining",
"" : "Unspecified"}


# WaDE Convert Multi-Beneficial Use to Single Primary Use Dictionary
# This has been built looking for unique items of only length = 2
WaDEBenUseDict = {
"Agriculture Irrigation,Aquaculture" : "Agriculture Irrigation",
"Agriculture Irrigation,Commercial/Industrial" : "Agriculture Irrigation",
"Agriculture Irrigation,Domestic" : "Agriculture Irrigation",
"Agriculture Irrigation,Livestock" : "Agriculture Irrigation",
"Agriculture Irrigation,Other" : "Agriculture Irrigation",
"Agriculture Irrigation,Public Supply" : "Agriculture Irrigation",
"Agriculture Irrigation,Recreation" : "Agriculture Irrigation",
"Agriculture Irrigation,Unspecified" : "Agriculture Irrigation",
"Aquaculture,Recreation" : "Recreation",
"Commercial/Industrial,Domestic" : "Commercial/Industrial",
"Commercial/Industrial,Livestock" : "Commercial/Industrial",
"Domestic,Fire" : "Domestic",
"Domestic,Livestock" : "Livestock",
"Domestic,Municipal Irrigation" : "Municipal Irrigation",
"Domestic,Other" : "Domestic",
"Domestic,Public Supply" : "Public Supply",
"Domestic,Unspecified" : "Domestic",
"Fire,Livestock" : "Livestock",
"In-stream Flow,Unspecified" : "In-stream Flow",
"Livestock,Municipal Irrigation" : "Municipal Irrigation",
"Livestock,Other" : "Livestock",
"Livestock,Unspecified" : "Livestock",
"Public Supply,Unspecified" : "Public Supply",
"Reservoir Storage,Unspecified" : "Reservoir Storage"}




# Function
############################################################################
def retrievePrimaryUseCategory(val):
    # Clean val & create list.
    valList = val.split(",")
    valList = sorted(list(map(lambda x: str(x).strip().lower(), valList)))

    # Temp converting native ben use to WaDE terminology ben use
    # Using get() to retrieve items from dictionary for list
    wbuList = sorted(list(map(lambda x: BUtoWBUDict[x], valList)))

    # Assign PrimaryUse
    # if len = 2, use dictionary
    # if not, return first item in list as string
    if len(wbuList) == 2:
        try:
            outString = WaDEBenUseDict[",".join(str(x) for x in wbuList)]
        except:
            outString = wbuList[0]
    else:
        outString = wbuList[0]
        outString = str(outString).strip()

    return outString